export const wells = [
  { id: "well-1", name: "UBIT BRAVO", wellId: "GB-05" },
  { id: "well-2", name: "UBIT ALPHA", wellId: "GA-03" },
  { id: "well-3", name: "UBIT CHARLIE", wellId: "GC-01" },
  { id: "well-4", name: "UBIT GOLF", wellId: "GG-02" },
  { id: "well-5", name: "UBIT HOTEL", wellId: "GB-08" },
];

export const baselines = {
  "well-1": {
    downhole_pressure: 4000,
    downhole_temp: 70,
    tubing_head_pressure: 1200,
    casing_pressure: 900,
    flow_line_pressure: 420,
    flow_line_temp: 47,
    battery_voltage: 12.9,
    battery_level: 82,
  },
  "well-2": {
    downhole_pressure: 3500,
    downhole_temp: 65,
    tubing_head_pressure: 1100,
    casing_pressure: 850,
    flow_line_pressure: 390,
    flow_line_temp: 43,
    battery_voltage: 12.6,
    battery_level: 75,
  },
  "well-3": {
    downhole_pressure: 4800,
    downhole_temp: 90,
    tubing_head_pressure: 1400,
    casing_pressure: 1050,
    flow_line_pressure: 500,
    flow_line_temp: 55,
    battery_voltage: 13.1,
    battery_level: 90,
  },
  "well-4": {
    downhole_pressure: 2800,
    downhole_temp: 55,
    tubing_head_pressure: 950,
    casing_pressure: 700,
    flow_line_pressure: 310,
    flow_line_temp: 38,
    battery_voltage: 12.2,
    battery_level: 60,
  },
  "well-5": {
    downhole_pressure: 3200,
    downhole_temp: 78,
    tubing_head_pressure: 1050,
    casing_pressure: 800,
    flow_line_pressure: 350,
    flow_line_temp: 50,
    battery_voltage: 12.8,
    battery_level: 70,
  },
};
